import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactLenis from "lenis/react";

const amiga = localFont({
  src: "../assets/fonts/amiga4ever.woff2",
  variable: "--font-amiga",
  display: "swap",
  preload: true,
});

const dystopian = localFont({
  src: "../assets/fonts/Sddystopian.otf",
  variable: "--font-dystopian",
  preload: true,
});

const orbitron = localFont({
  src: "../assets/fonts/Orbitron-VariableFont.ttf",
  variable: "--font-orbitron",
  preload: true,
});

const delagothic = localFont({
  src: "../assets/fonts/DelaGothicOne-Regular.ttf",
  variable: "--font-delagothic",
  preload: true,
});

const kleemax = localFont({
  src: "../assets/fonts/kleemax.ttf",
  variable: "--font-kleemax",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${amiga.variable} ${dystopian.variable} ${delagothic.variable} ${orbitron.variable} ${kleemax.variable} antialiased`}
      >
        <ReactLenis root />
        {children}
      </body>
    </html>
  );
}
