import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const amiga = localFont({
  src: "../assets/fonts/amiga4ever.woff2",
  variable: "--font-amiga",
  display: "swap",
  preload: true,
});

const dystopian = localFont({
  src: "../assets/fonts/Sddystopian.otf",
  variable: "--font-dystopian",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${amiga.variable} ${dystopian.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
